import React from 'react'
import Head from 'next/head'
import Sidenavbar from '../adminpanel/Sidenavbar'
import UploadProject from '../adminpanel/UploadProject'

function adminpanel() {
    return (
        <>
            <Head>
                <title>Admin Panel</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
                    integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
                    crossOrigin="anonymous"
                    referrerPolicy="no-referrer"
                />
            </Head>
            <div className="w-full mx-auto max-w-8xl">
                <div className='lg:flex'>
                    <aside className='inset-0 z-20 h-fit lg:h-screen flex-none fixed top-0 w-[15rem] block shadow'>
                        <Sidenavbar />
                    </aside>
                    <main className='flex-auto min-w-0 lg:static lg:max-h-full lg:overflow-visible min-h-screen w-[calc(100%-15rem)] lg:ml-[15rem]'>
                        <UploadProject/>
                    </main>
                </div>
            </div>
        </>
    )
}

export default adminpanel
