import Head from 'next/head'
import Header from '../components/Header'
import Main from '../components/Main'
import Skills from '../components/Skills'
import About from '../components/About'
import Projects from '../components/Projects'
import Education from '../components/Education'
import Contact from '../components/Contact'
import { createRef, useEffect, useRef } from 'react'
export default function Home() {
  const scrolltoabout = createRef();
  const scrolltoskill = useRef();
  const scrolltoproject = useRef();
  const scrolltocontact = useRef();
  const scrollToAbout=(e)=>{
    e.preventDefault();
    console.log(scrolltoabout.current);
    scrolltoabout.current.scrollIntoView({block:"center"})
  }
  const scrollToSkill=()=>{
    console.log(scrolltoskill.current);
    scrolltoskill.current.scrollIntoView({block:"center"})
  }
  const scrollToProject=()=>{
    scrolltoproject.current ?. scrollIntoView(false)
  }
  const scrollToContact=()=>{
    scrolltocontact.current?.scrollIntoView({block: "start", inline: "nearest"})
  }
  
  
  return (
    <div className="bg-black text-black">
      <Head>
        <title>Ayush Sharma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header scrollToAbout = {scrollToAbout} scrollToSkill = {scrollToSkill} scrollToProject = {scrollToProject} scrollToContact = {scrollToContact}/>
      <Main />
      <div ref={scrolltoabout}><About/><br /></div>
      <div ref={scrolltoskill}><Skills/><br /></div>
      <Education/>
      <Projects scroll={scrolltoproject}/>
      <Contact scroll={scrolltocontact}/>
    </div>
  )
}
