import Head from 'next/head'
import Header from '../components/Header'
import Main from '../components/Main'
import Skills from '../components/Skills'
import About from '../components/About'
import Projects from '../components/Projects'
import Education from '../components/Education'
import Contact from '../components/Contact'
export default function Home() {

  return (
    <div className="w-full place-items-center bg-[#202427] text-black container mx-auto translate-y-1">
      <Head>
        <title>Ayush Sharma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Main />
      <About /><br />
      <Skills /><br />
      <Education />
      <Projects/>
      <Contact/>
    </div>
  )
}
